theme: jekyll-theme-hacker
title: Vladimir Roncevic
description: Biography
author: vroncevic 
url: "https://vroncevic.github.io" 
baseurl: "/" 
permalink: /posts/:year-:month-:day-:title 
lang: en 
show_lang_in_post_listings: true 
feed_limit: 25
styles: 
  brand-color: "#151515" 
  link-text-decoration: none 
disqus:
  shortname:
google_analytics:


# Sidebar settings
sidebar: 
  pages: true 
  categories: false
  tags: false
  contact: true 
  legal: true 

slides:
  theme: solarized 
  data-separator: "^\\r?\\n-----\\r?\\n$" 
  data-separator-vertical: "^\\r?\\n---\\r?\\n$" 
  data-separator-notes: "^Notes:" 


defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: "categories"
    values:
      layout: "category"
  -
    scope:
      path: "tags"
    values:
      layout: "tag"

limit_posts: 0 
future: false 
unpublished: false 
show_drafts: false 

markdown: kramdown
highlighter: rouge
excerpt_separator: "\n\n"
profile: false 

kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  entity_output: as_char
  toc_levels: 1..6
  footnote_nr: 1
  smart_quotes: lsquo,rsquo,ldquo,rdquo
